// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MLTrackingML.Model
{
    public class ModelInput
    {
        [ColumnName("begin"), LoadColumn(0)]
        public string Begin { get; set; }


        [ColumnName("end"), LoadColumn(1)]
        public string End { get; set; }


        [ColumnName("duration"), LoadColumn(2)]
        public float Duration { get; set; }


    }
}
